config/routes.rb
Dayrobot::Application.routes.draw do

	
	
  get "tags/new"

	resources :users
	resources :entries
	resources :sessions, :only => [:new, :create, :destroy]
	resources :tags
	
	match '/register', :to => 'users#new'
	match '/login', :to => 'sessions#new'
	match '/logout', :to => 'sessions#destroy'
	match '/newtag', :to => 'tags#new'
	
	get "pages/home"
	
	get "pages/about"
	
	get "home/about"
	
	
	
	root :to => "pages#home"
	  
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	attr_accessible :content, :entry_date
	
	belongs_to :user
	
	default_scope :order => 'entries.created_at DESC'
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	attr_accessible :tag
	
	belongs_to :user

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	
	has_many :entries, :dependent => :destroy
	has_many :tags, :dependent => :destroy
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :name, :presence => true,
				     :length => { :maximum => 50 }
				     
	validates :email, :presence => true,
					  :format => {:with => email_regex },
					  :uniqueness => { :case_sensitive => false }
	
	validates :password, :presence => true,
						 :confirmation => true,
						 :length => { :within => 6..40 }
						 
	before_save :encrypt_password
	
	def has_password?(submitted_password)
		# compare encrypted_password with the encrypted version of submitted_password
		self.encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = User.find_by_email(email)
		# return nil if no such user
		return nil if user.nil?
		# return user object if password is good
		return user if user.has_password?(submitted_password)
		# returns nil at end of method in case of password mismatch
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
		user = User.find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end
	
	private
		
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(self.password)
		end
		
		def encrypt(string)
			secure_hash("#{self.salt}--#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{self.password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	require 'mail'
	skip_before_filter :verify_authenticity_token
	
	def create
		
		message = Mail.new(params[:message])
		
		date_regex = 'what did you do today\?\s\((\d{4}-\d{2}-\d{2})\)'
			
		if message.subject.match(date_regex)
			entry_date_string =  message.subject.match(date_regex)[1]
			entry_date = Date.strptime(entry_date_string, '%F')
		else
			entry_date = "nope"
			#render :text => 'failure', :status => 404
		end
		
		message_from = message.from
		
		@user = User.find_by_email(message_from)
		
		if @user.nil?
			# handle
		else		
			content = "#{message.parts[0].body.decoded} - from: #{message.from}"
			@user.entries.create!(:entry_date => entry_date, :content => content)
			render :text => 'success', :status => 200
		end
	end
		
	def index
		@entries = Entry.all
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   @title = "login"
  end
  
  def create
  	user = User.authenticate(params[:session][:email],
  							 params[:session][:password])
  	if user.nil?
  		flash.now[:error] = "invalid email/password combo"
  		@title = "login"
  		render 'new'
  	else
  		DayRobot.bot_email(user).deliver
  		login user
  		redirect_to user
  	end
  	
  end
  
  def destroy
  	logout
  	redirect_to root_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	def new
	  @tag = Tag.new
	  @title = "tags"
	end
	
	def create
		@user = current_user
		@user.tags.create(:tag => params[:tag][:tag])
		redirect_to user_path(@user)
	end
	
	def show
		@user = current_user
		@tag = Tag.find(params[:id])
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 	def new
  		@user = User.new
  		@title = "register"
	end
	
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end
	
	def create
		@user = User.new(params[:user])
		if @user.save
			DayRobot.welcome_email(@user).deliver
			login @user
			flash[:success] = "welcome to dayrobot."
			redirect_to user_path(@user)
		else
			@title = "register"
			render 'new'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis
	def title
		base_title = "* dayrobot *"
		if @title.nil?
			base_title
		else
			"#{base_title} #{@title}"
		end
	end
	
	# highlights proper nav link
	
	def nav_link(link)
		if @title == link
			return "selected_nav_link" 
		else
			return "unselected_nav_link"
		end
	end
	
	def tagger(raw_entry, selected_tag="lkjfklsdjf")
		
		tagged_entry = raw_entry
		
		@user.tags.find_each do |tag_row|
			tag = tag_row.tag
			tagged_entry = tagged_entry.gsub(/\b(#{tag})\b/i, "<a href='\\\\tags\\\\#{tag_row.id}' class='tagged'>\\1</a>")
		end
		
		#highlight selected tag, if any
		tagged_entry = tagged_entry.gsub(/class='(tagged)'>#{selected_tag}/i, "class='selected_tag'>#{selected_tag}")
		
		
		return tagged_entry
	
	end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user 
		@current_user ||= user_from_remember_token
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def logout
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	private
		
		def user_from_remember_token
			User.authenticate_with_salt(*remember_token) # * lets us use two element array when two params expected
		end
		
		def remember_token
			cookies.signed[:remember_token] || [nil, nil] # for tests, see tutorial ch. 9
		end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/day_robot/bot_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>tell me now <%= @user.name %></h1>
    
    <p>love,<br>dayrobot</p>
  </body>
</html>

app/views/day_robot/bot_email.text.erb
tell me now <%= @user.email %>.

love,

dayrobot

app/views/day_robot/welcome_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>welcome to dayrobot, <%= @user.name %></h1>
    <p>
      your username is: <%= @user.email %>.<br/>
    </p>
    <p>
      to login to the site, just follow this link: <%= @url %>.
    </p>
    <p>love,<br>dayrobot</p>
  </body>
</html>

app/views/day_robot/welcome_email.text.erb
welcome to dayrobot, <%= @user.name %>
===============================================

your username is: <%= @user.email %>.
 
to login to the site, just follow this link: <%= @url %>.
 
love,

dayrobot

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>User_Id</th>
    <th>Entry Date</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.user_id %></td>
    <td><%= entry.entry_date %></td>
    <td><%= entry.content %></td>
  </tr>
<% end %>
</table>

<br />

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "about", '#' %></li>
      <li><%= link_to "contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<ul>
			<li><%= link_to "dayrobot", root_path, :id => "logo" %></li>
			
			<% if logged_in? %>
				<li><%= link_to "me", current_user %></li>
				<li><%= link_to "tags", newtag_path %></li>
				<li><%= link_to "logout", logout_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to "login", login_path, :class => nav_link("login") %></li>
				<li><%= link_to "register", register_path, :class => nav_link("register") %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->  
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= javascript_include_tag :defaults %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tag %>
</head>
	<body>
		<div class="container">
		<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<br>
        <%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>welcome to dayrobot.</h1>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/new.html.erb
<h1>add a tag</h1>

<%= form_for(@tag) do |f| %>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag, :class => "text_input" %>
  </div>
 
  <div class="actions">
    <%= f.submit "add tag" %>
  </div>
<% end %>

app/views/tags/show.html.erb
<h1>
	<%= @tag.tag %>
</h1>

<table class="entries">
	<% @user.entries.find_by_sql("SELECT * FROM entries WHERE content  #{DATABASE_OPERATOR[:like_operator]} '%#{@tag.tag}%' ORDER BY entry_date DESC").each do |entry| %>
	  <tr class="entry">
		<td><%= entry.entry_date %></td>
		<td><%= raw tagger(entry.content, @tag.tag) %></td>
	  </tr>
	<% end %>
</table>

app/views/users/new.html.erb
<h1>register for dayrobot.</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "text_input" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, :class => "text_input" %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :class => "text_input" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation, :class => "text_input" %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>
	<%= @user.name %>
</h1>
<table class="entries">
	
	
	<% @user.entries.order("entry_date DESC").each do |entry| %>

	
	  <tr class="entry">
		<td><%= entry.entry_date %></td>
		<td><%= raw tagger(entry.content) %></td>
	  </tr>
	<% end %>
</table>